### PR TITLE
refactor(generate): take a functional approach

### PR DESCRIPTION
**Pull request by adnasa**
I found the `generateDataFromMeasures` function to be hard to understand and here is my attempt to apply a functional approach to it. 😝 

- moves sort function to be inline and executed last
- `alignComponents` was used once, so it didn't make sense that this is a function in the file, unless we wanted this tested
- getTotalTime renamed to getSummarisedTimeSpent

### CODE REVIEW

**Comment by nitin42** [comment]
Oh! Great, thanks. But some tests are failing 🤔

**Comment by adnasa** [comment]
hmmm. That’s weird. Locally they worked?
I ran then in node 8.2.0.
It could be that Object.entries is not supported yet on CI

**Comment by adnasa** [comment]
I couldn’t open and get an review the CI result btw

**Comment by adnasa** [comment]
haaaaa, I just figured. `Object.entries` is not supported just yet.
I'll spin up a fix that uses `Object.keys` instead.

**Comment by adnasa** [comment]
@nitin42 all good now. please review

**Comment by adnasa** [comment]
@nitin42 any chance you can review this?

**Comment by nitin42** [comment]
Hey, thanks for the PR. Sorry I've been busy lately with maintaining some other projects. I'll review this later sometime today or may be tomorrow.

**Comment by nitin42** [comment]
Thank you so much!

**Pull request merged**
