### PR TITLE
New ui

### PR DESCRIPTION
**Pull request by ranjith29h**
updated new button style and result component

### CODE REVIEW

**Comment by nitin42** [comment]
Hey! That's a good start. I think this still needs some more changes. You've replaced the `Results` component with a table but the table doesn't depict any information about the stats. This may confuse the developer inspecting the measures.

**Comment by ranjith29h** [comment]
So what we can do to represent `Results` component

**Comment by selbekk** [comment]
Would love some screenshots of the new UI :D

**Comment by nitin42** [comment]
I'd say that, don't create an another table for displaying the results. You could work on making the UI look a little elegant (may be change the fonts, table border or integrate bootstrap to customise the table UI).

**Comment by nitin42** [comment]
Merged #21

**Pull request closed without merging**
